name: Build Release 


on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and activate venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install Requirements 
        run: pip3 install -r requirements-build.txt  

      - name: Build linux executable 
        run: pyinstaller main.py --onefile -n pixeldrainer-linux

      - name: Make static executable
        run: staticx dist/pixeldrainer-linux build/pixeldrainer-linux

      - name: Upload executable
        uses: softprops/action-gh-release@v2
        with:
          files: build/pixeldrainer-linux-static
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
