name: Build Release 


on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'

      - name: Install pyinstaller 
        run: pip install pyinstaller

      - name: Build linux executable 
        run: pyinstaller main.py --onefile -n pixeldrainer-linux

      - name: Upload executable
        uses: softprops/action-gh-release@v2
        with:
          files: dist/pixeldrainer-linux
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
